CREATE TABLE IF NOT EXISTS user (	
id INTEGER PRIMARY KEY,
usuario TEXT NOT NULL,
email TEXT NOT NULL,
senha TEXT NOT NULL,
adm INTEGER DEFAULT 0 NOT NULL,
gestor INTEGER DEFAULT 0 NOT NULL,
coordenador INTEGER DEFAULT 0 NOT NULL,
propositor INTEGER DEFAULT 0 NOT NULL,
cursista INTEGER DEFAULT 0 NOT NULL,
apoiador INTEGER DEFAULT 0 NOT NULL
);

--turma_id_user = professor
CREATE TABLE IF NOT EXISTS turma(
id_turma INTEGER PRIMARY KEY AUTOINCREMENT,
turma_id_professor INTEGER NOT NULL,
codigo VARCHAR(50) NOT NULL,
curso VARCHAR(50) NOT NULL,
aulas INTEGER DEFAULT '0' NOT NULL,
FOREIGN KEY (turma_id_professor) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS horario(
id_horario INTEGER PRIMARY KEY AUTOINCREMENT,
horario_id_turma INTEGER NOT NULL,
dia_da_semana VARCHAR(20) NOT NULL,
horario_inicio TIME NOT NULL,
horario_termino TIME NOT NULL,
FOREIGN KEY (horario_id_turma) REFERENCES turma(id_turma)
);

CREATE TABLE IF NOT EXISTS alunos(
id_aluno INTEGER PRIMARY KEY AUTOINCREMENT,
alunos_id_turma INTEGER NOT NULL,
alunos_id_user INTEGER NOT NULL,
presenca INTEGER DEFAULT '0' NOT NULL,
FOREIGN KEY (alunos_id_turma) REFERENCES turma(id_turma),
FOREIGN KEY (alunos_id_user) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS userComplemento(
id_complemento INTEGER PRIMARY KEY AUTOINCREMENT,
id_do_user INTEGER NOT NULL,
tag VARCHAR(20) NOT NULL,
profissao VARCHAR(40) NOT NULL,
funcao VARCHAR(30) NOT NULL,
superentendenciaDaSUBPAV VARCHAR(20) NOT NULL,
CAP VARCHAR(20) NOT NULL,
unidadeBasicaDeSaude VARCHAR(40) NOT NULL,
FOREIGN KEY (id_do_user) REFERENCES user(id)
);

